dataset_name: swdd
language: zh
screener_model: /home/tos_lx/basemodel/gte-small-zh
model_name: /home/tos_lx/basemodel/Qwen3-Embedding-0.6B
pooling_strategy: last_token
gradient_checkpointing: true
max_risk_posts: 32
global_history_max_per_segment: 128
encoder_pretrain_batch_size: 32
batch_size: 64
scored_path: ../dataset/weibo/SWDD/score_data/depressed.scored.jsonl
cleaned_path: ../dataset/weibo/SWDD/cleaned_data/control.cleaned.jsonl
processed_dir: data/processed/swdd
train_path: data/user_samples/swdd_train.jsonl
val_path: data/user_samples/swdd_val.jsonl
test_path: data/user_samples/swdd_test.jsonl
scored_posts_path: data/processed/swdd/depressed_scored_posts.jsonl
encoder_save_path: data/models/swdd_qwen3_encoder_pretrained.pt
warmstart_save_path: data/models/swdd_qwen3_warmstart_experts.pt
save_path: data/models/swdd_qwen3_final_model.pt
log_path: data/models/swdd_qwen3_training_log.json
